name: Upload YouTube Video

on:
  schedule:
    - cron: "0 22 * * *"  # Runs daily at 4 PM UTC (adjust as needed)
  workflow_dispatch:  # Allows manual trigger

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests

      - name: Download video from Google Drive
        run: |
          FILE_ID="1hTozBu_-VZNWRj3G8SQB3ya-HtdknwFQ"
          FILE_NAME="video.mp4"
          wget --no-check-certificate "https://drive.google.com/uc?export=download&id=$FILE_ID" -O $FILE_NAME


      - name: Upload video to YouTube
        env:
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        run: python upload_video.py
