# name: Upload YouTube Video

# on:
#   schedule:
#     - cron: "0 22 * * *"  # Runs daily at 4 PM UTC (adjust as needed)
#   workflow_dispatch:  # Allows manual trigger

# jobs:
#   upload:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"

#       - name: Install dependencies
#         run: pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests

#       - name: Install gdown and download video
#         run: |
#           pip install gdown
#           gdown --id 1jcv7wt2Jm042EGVr55TqNh0tkaRvbYoZ -O video.mp4


#       - name: Upload video to YouTube
#         env:
#           YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
#           YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
#           YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
#         run: python upload_video.py
